name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

env:
  HEX_API_KEY: ${{ secrets.HEX_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: elixir
          package-name: mongodb_driver

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup BEAM
        if: ${{ steps.release.outputs.release_created }}
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          elixir-version: "1.17.2"

      - name: Install Hex + Rebar
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: mix deps.get

      - name: Compile
        if: ${{ steps.release.outputs.release_created }}
        run: mix compile

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: mix hex.build

      - name: Publish to Hex
        if: ${{ steps.release.outputs.release_created }}
        run: mix hex.publish --yes